### ISSUE TITLE
URL isn't highlighted (selected) when clicking into the address bar

### ISSUE THREAD

**Issue by TheOnlineUser** [god-s-perfect-idiot/metro-browser-native#26]
Most browsers make it so that when you click/tap the address bar, the entire URL is automatically selected so you can just start typing and replace what's in there.

As it is now, you'd have to hold the backspace down for a long time, or manually select it all (requiring extra steps).

**Comment by god-s-perfect-idiot** [comment]
related: https://github.com/god-s-perfect-idiot/metro-browser-native/issues/13

**Comment by god-s-perfect-idiot** [comment]
fixed Thanks! @TheOnlineUser
