### ISSUE TITLE
Favorites doesn't work

### ISSUE THREAD

**Issue by TheOnlineUser** [god-s-perfect-idiot/metro-browser-native#27]
I can add a page to my Favorites (currently spelled Favourites in the app, UK spelling, may or may not be intentional), but clicking the page from the Favorites page doesn't load the page. Nothing happens.

**Comment by god-s-perfect-idiot** [comment]
fixed
https://github.com/god-s-perfect-idiot/metro-browser-native/commit/80c6276f160a6ae59a22c0fcc0f068c67da23116
