### ISSUE TITLE
"Recents" (history) doesn't work

### ISSUE THREAD

**Issue by TheOnlineUser** [god-s-perfect-idiot/metro-browser-native#28]
Clicking a page in my history (Recents) page doesn't load the page. Nothing happens when you click past viewed pages. It is saving history correctly but just not loading them.

**Comment by god-s-perfect-idiot** [comment]
fixed
https://github.com/god-s-perfect-idiot/metro-browser-native/commit/80c6276f160a6ae59a22c0fcc0f068c67da23116
